### ISSUE TITLE
加入别人房间时明明有mod但是立刻被踢出

### ISSUE THREAD

**Issue by ponyzerteal** [Bidge-CTG/SNR-CTG#1]
我们都有mod，但是只能自己一个人创房间，别人进不来，有什么解决办法吗

**Comment by Bidge-CTG** [comment]
您的Mod是否安装正常？
如果是 请按照下面的方法解决
1、将AmongUs文件夹除了AmongUs.exe以外的文件删掉，将懒人包解压到此文件夹 。
这可以解决大部分问题 
若遇到无法登陆的问题 请发邮件到3448851731@qq.com
